### ISSUE TITLE
Pushing to Local Dokku

### ISSUE THREAD

**Issue by xadves** [etewiah/property_web_builder#58]
Not very clear on local installation. Tried building from Ruby on Rails and wasn't very successful. Deployment to Dokku is favored, but when I deploy locally I get the "We're sorry, something went wrong". Suggested to view logs, but I cannot find them. Suggestions? This is a clean installation of Ubuntu Server 16 and Dokku.

**Comment by etewiah** [comment]
Without the logs it is close to impossible for me to know what went wrong.  

It would also help if you actually tell me the steps you took.  See:

https://github.com/etewiah/property_web_builder/wiki/Guide-to-creating-issues

**Comment by xadves** [comment]
I looked in /var/logs for the logs and there was nothing there seemed to be from property web builder .I can upload similar event logs if that will help but I'm not sure that much will be relevant.

I did a very basic setup. I installed Ubuntu server 16.04.3to a VM with only the SSH option enabled, then immediately downloaded and installed Dokku exactly as the website says. Git cloned the directory you linked for pwb on heroku, and pushed it. Everything seemed to go fine, and even deployed. Went to the ip:port and thats where I get the "We're sorry..." bit. I prefer to launch this via Dokku for ease of deployment. Has this been done before? What event logs would you like from my Dokku server?

**Comment by etewiah** [comment]
Hi Sam, it is hard to communicate the frustration of having to deal with issues like this which I cannot possibly help with.  I've uploaded a short video response:

https://youtu.be/w2kEWGFEFOU

I hope seeing the video and realising there is a human being rather than a robot behind this project might motivate you to spend those extra few minutes actually telling me some useful information that can help me help you.

**Comment by xadves** [comment]
I am very well aware you are a human, and not a robot. I want to work with you and contribute the best I can since your documentation does not include much about localized installations. That's why I asked questions seeking the relevant data, aka the location of your log files for this project and if you have ever used dokku which you did not reply with. So since you want to know what I've done, here's the guides to Dokku I've used, which I followed, only replacing the relevant data with this project.

https://github.com/dokku/dokku - To install Dokku on a completely clean install of Ubuntu 16.04.3.
http://dokku.viewdocs.io/dokku/deployment/application-deployment/ - To deploy your application to Dokku.

And this was the only logs I got from Dokku about pwb:
[pwb.log](https://github.com/etewiah/property_web_builder/files/1692498/pwb.log)

**Comment by etewiah** [comment]
Hi @xadves, the extra information you've provided helps a lot.  I now know which instructions you followed and I was able to review them.  The first thing that seemed strange was that there was no mention of migrations in the instructions.
The logs are also super useful.   In there it is clear from this line that there has been an issue with the migrations:

`Table "pwb_websites" doesn't exist.  Have all migrations been run?`

I suspect you used this repo (which is a ruby on rails engine rather than a full app) instead of the "pwb-for-heroku".   Please confirm which repo you used.  

If you list the commands you typed in your console, that will also save me asking you more questions for clarification.  (You can type 'history' in your console to list everything you typed)

When we get to the bottom of this can you please document everything here to help others in the future:
https://github.com/etewiah/property_web_builder/wiki/Deploying-to-Dokku

Apologies if I came across as a bit aggressive in the video - that wasn't my intention ;)

**Comment by xadves** [comment]
[history.log](https://github.com/etewiah/property_web_builder/files/1693171/history.log)

I agree, I got worried I did the clone the wrong, but I checked the history and I did clone the correct repo.

**Comment by etewiah** [comment]
Okay, so it seems dokku would have used the app.json file here to figure out that it needs to run a migration after deploy:

https://github.com/etewiah/pwb-for-heroku/blob/master/app.json

I know I accidentally made a commit with some errors a couple of weeks ago.  It seems this is likely what has caused the error you encountered.  Can you please try again with the most recent version of pwb-for-heroku and let me know how it goes?

BTW, it makes it a bit easier to paste long error files etc into a gist:

https://gist.github.com/etewiah/b53b93cfedeedc44d49d624c664be60b

**Comment by xadves** [comment]
Got the same error screen:
https://gist.github.com/xadves/7d36271e919cd42d923e9d6a4e970093

**Comment by etewiah** [comment]
Can you provide a bit more of the error log?

You can see that in the previous log you gave me, lines 83-100 tell me what happened before the error stack:

https://gist.github.com/etewiah/b53b93cfedeedc44d49d624c664be60b

In the last log, that bit is missing.
