### ISSUE TITLE
Importing/exporting photos.

### ISSUE THREAD

**Issue by vvalchev** [etewiah/property_web_builder#69]
I'm researching how to easily migrate existing agency properties to Property Web Builder.
Unfortunately the CSV file format doesn't support photos.

I've found https://github.com/etewiah/property_web_builder/blob/master/config/import_mappings/api_pwb.json which includes 'property-photos' field, by I don't know how to use this api_pwb. Also the file doesn't provide enough information - are the images base64 encoded or use some other encoding?

Checked the exported from PWB csv file, but the photos are not included there.
And how do you map multiple photos in a since csv column, what separator is used?

**Comment by etewiah** [comment]
Hi @vvalchev , I didn't get to finish work on the CSV imports so yes you will find it does not yet support photos.

I found a lot of people wanted to import properties from existing websites so I put more work into that and there is support for importing photos from other websites.  You can find instructions about that here:

https://github.com/etewiah/property_web_builder/wiki/Using-the-PropertyWebScraper-gem-to-import-listings

Since I moved the property import functionality to a seperate project there is now some code in PWB that I no longer use and the json file you mentioned is one of those.  Sorry for the confusion - I will clean out the redundant code as soon as I get the chance.

If you need help with importing from a website that is not supported by property_web_scraper I can help you set up support for it.  Just let me know and we can arrange a skype call.
